services:
  dw:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=$DW_NAME
      - POSTGRES_USER=$DW_USER
      - POSTGRES_PASSWORD=$DW_PASSWORD
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:v0.56.8.x
    container_name: crypto_tracker_metabase
    depends_on:
      dw:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: $METABASE_DB
      MB_DB_PORT: 5432
      MB_DB_USER: $DW_USER
      MB_DB_PASS: $DW_PASSWORD
      MB_DB_HOST: dw

  app:
    build: .
    depends_on:
      dw:
        condition: service_healthy
    env_file:
      - .env


volumes:
  postgres_data: